<?php
?>
<?php /** 
 * @var $block \Magento\Framework\Pricing\Render\Amount
 * @var \Magento\Framework\Escaper $escaper
 */
 ?>

<span class="price-container <?= $escaper->escapeHtmlAttr($block->getAdjustmentCssClasses()) ?>"
    <?= $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>>

    <?php if ($block->getDisplayLabel()) : ?>
        <span class="price-label"><?= $escaper->escapeHtml($block->getDisplayLabel()) ?></span>
    <?php endif; ?>
<span class="price-prefix"><?= $escaper->escapeHtml(__('Price')) ?></span>
    <span  <?php if ($block->getPriceId()) :?> id="<?= $block->escapeHtmlAttr($block->getPriceId()) ?>"<?php endif;?>
        <?= ($block->getPriceDisplayLabel()) ? 'data-label="' . $block->escapeHtmlAttr($block->getPriceDisplayLabel() . $block->getPriceDisplayInclExclTaxes()) . '"' : '' ?>
    data-price-amount="<?= $block->escapeHtmlAttr($block->getDisplayValue()) ?>"
    data-price-type="<?= $block->escapeHtmlAttr($block->getPriceType()) ?>"
        class="price-wrapper <?= $escaper->escapeHtmlAttr($block->getPriceWrapperCss()) ?>">
        <?= $escaper->escapeHtml($block->formatCurrency($block->getDisplayValue(), (bool)$block->getIncludeContainer()), ['span']) ?>
    </span>
    
    <?php if ($block->hasAdjustmentsHtml()) : ?>
        <?= $block->getAdjustmentsHtml() ?>
    <?php endif; ?>

    <?php if ($block->getSchema()) : ?>
        <meta itemprop="price" content="<?= $escaper->escapeHtmlAttr($block->getDisplayValue()) ?>" />
        <meta itemprop="priceCurrency" content="<?= $escaper->escapeHtmlAttr($block->getDisplayCurrencyCode()) ?>" />
    <?php endif; ?>
</span>
